### ISSUE TITLE
Add contributors section in README.md

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/react-simple-infinite-loading#10]
Add contributors section in README.md using [all-contributors](https://github.com/all-contributors/all-contributors)

**Comment by keremh** [comment]
hi, i want to work on this issue.

**Comment by frinyvonnick** [comment]
Hi @keremh, thank you for considering contributing to react-simple-infinite-loading 🙏 Feel free to open a pull request. If you need help ask here 👍

**Comment by aditya1rawat** [comment]
Can I work on this right now? Or is this already taken?

**Comment by frinyvonnick** [comment]
Hi @aditya1rawat 👋 @keremh already did it in the pull request #11. 

If you are looking for another good first issue to do there is the issue #6 👍
