### ISSUE TITLE
Add a mention of the example application in usage section

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/react-simple-infinite-loading#14]
We could add a mention to the [example app](https://github.com/frinyvonnick/react-simple-infinite-loading/tree/master/example) in the usage section of the README.

It could contains quick instructions to launch it.

**Comment by trblackw** [comment]
@frinyvonnick Hey I'd like to work on this! Please assign me if you would 😉

Also, just so I'm clear, within the usage section of _this_ repo's readme, you would like there to be a reference to the linked repo, including brief instructions with how to boot that project?

**Comment by frinyvonnick** [comment]
Hi @trblackw, thank you for considering contributing to `react-simple-infinite-loading` 🙏 

The example app is in the `example` folder. We have two options :

- Add a mention in the root README with brief instructions to boot the example project
- Add a link in the usage section of the root README to the README in example folder and change its content to include brief instructions to boot the example project

Which one do you prefer ?

**Comment by trblackw** [comment]
@frinyvonnick I'd say the former. I'm assuming this is my point of reference for boot instructions? https://github.com/frinyvonnick/react-simple-infinite-loading/tree/master/example#npm-start

**Comment by frinyvonnick** [comment]
@trblackw you can start from a fresh README in the example folder. This one was created by create-react-app and is a bit heavy.

**Comment by trblackw** [comment]
@frinyvonnick I'm a bit confused as I dig into this what you want done here. The CRA automated readme is accurate for describing how to boot the project, you just want to shorten it? i.e. make it less "heavy"?

**Comment by frinyvonnick** [comment]
Sure @trblackw, this generated README is nice for explaining `create-react-app` purpose and how it works, but in our case we want simple explanations:

- How to install dependencies
- How to launch the example project

Is it more clear ?

**Comment by trblackw** [comment]
To be honest, it's not clear how modifying the verbiage that's already in place would make the boot of the project easier? I'm struggling to see how any reduction in the CRA verbiage would benefit your project in terms of simplicity.

**Comment by frinyvonnick** [comment]
No problem, @trblackw thank you for the discussion 👍
