### ISSUE TITLE
Add a placeholder property 

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/react-simple-infinite-loading#18]
We should add the possibility to display a placeholder component if the data isn't loaded yet.

[src/index.js](https://github.com/frinyvonnick/react-simple-infinite-loading/blob/master/src/index.js) line 47
```diff
{({ index, style }) => (
  <div style={style}>
-  {children[index]}
+  {children[index] || placeholder}
  </div>
)}
```

We should verify if children[index] exists otherwise we display a placeholder component passed as prop by the user.

**Comment by trybick** [comment]
I can try this!
