### ISSUE TITLE
Improve example with a working loadMoreItems functionality

### ISSUE THREAD

**Issue by Orodan** [frinyvonnick/react-simple-infinite-loading#24]
I think its great to have a working example, but it could use some improvements, like using the `loadMoreItems` functionality :)

I also think we can improve the ui of the example to make it looks like a bit better.

**Comment by Orodan** [comment]
And if we agree it's needed, I'll work on it obviously :D

**Comment by frinyvonnick** [comment]
Sure @Orodan 👍 This is related to #13. I'll close this one you can ask questions in the other issue 😄
