### ISSUE TITLE
Pass down a itemsCount property

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/react-simple-infinite-loading#28]
`react-simple-infinite-loading`  handles the `itemsCount`  property from `react-window-infinite-loader`  to simplify its usage for infinite loading streams like Twitter or Facebook feeds. Sometimes you already know the items count. It would be nice to add an itemsCount property to [`InfiniteLoader`](https://github.com/frinyvonnick/react-simple-infinite-loading/blob/master/src/index.js#L36) component to avoid having the scrollbar changing its size as the items being loaded.

**Comment by gVirtu** [comment]
I'd like to take a stab at this one! :)
Looks simple enough, I'll have something up shortly and will let you know.

**Comment by frinyvonnick** [comment]
Thank you @gVirtu for considering contributing to `react-simple-infinite-loading` 🙏 Ask if you have any questions 👍

**Comment by gVirtu** [comment]
I'm really liking how clean the code currently is and I'd love to keep it that way!
So I would like to ask your opinion on which approach looks better:

Currently the `itemsCount` is calculated as
```js
const itemsCount = hasMoreItems ? children.length + 1 : children.length
```

Now, by adding an optional `itemsCount` prop, we make sure it overrides this calculation when applicable, so I was thinking either:

 1. Having it as a nested ternary. Simple enough, but is it legible according to our standards?
```js
const effectiveCount = (itemsCount !== undefined) 
                       ? (itemsCount) 
                       : (hasMoreItems ? children.length + 1 : children.length)
```

 2. Factoring out this logic to a function. Though I noticed we have no other utility functions so far, so this may be overkill.
```js
function getEffectiveCount(itemsCount, hasMoreItems, childrenLength) {
  if (itemsCount === undefined)
    return hasMoreItems ? childrenLength + 1 : childrenLength
  return itemsCount
}
```

Just to make sure this tiny improvement meets the project's long term expectations. :)
Thanks!

**Comment by frinyvonnick** [comment]
@gVirtu thank you for the compliment ❤️ 

Really interesting propositions, I prefer the second one. I have a third approach which imho is halfway of yours:

```js
let effectiveCount = itemsCount 
if (effectiveCount === undefined) {
    effectiveCount = hasMoreItems ? childrenLength + 1 : childrenLength
}
```
It avoids having nested ternaries. What do you think of it?

**Comment by gVirtu** [comment]
I like it! Simple and straightforward. I'll go with it.
Thanks for the input!
