### ISSUE TITLE
Add the possibility to pass down a ref to InfiniteLoader

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/react-simple-infinite-loading#4]
InfiniteLoader component has a function called [resetloadMoreItemsCache](https://github.com/bvaughn/react-window-infinite-loader/blob/master/src/InfiniteLoader.js#L49) that clear the cache. It is really useful for infinite loading list that have predicates or sort options.

To make this function available we need to wrap InfiniteLoading component with a [forwardRef](https://en.reactjs.org/docs/forwarding-refs.html) since it is a functionnal component and pass down the ref to InfiniteLoader component.

**Comment by henry-ns** [comment]
can I do it?

**Comment by frinyvonnick** [comment]
Hi @henry-ns, Thank you for considering contributing to `react-simple-infinite-loading` 🙏 Sure, you can! Here is a [documentation](https://github.com/bvaughn/react-window-infinite-loader#advanced-usage) that can help to do it. If you have any trouble, ask your questions here 👍
