### ISSUE TITLE
Extract dependencies from the bundle

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/react-simple-infinite-loading#5]
The dependencies listed in `package.json` are bundled. It would be better to use the version installed in `node_modules`.

**Comment by frinyvonnick** [comment]
The following dependencies should be declared as externals:

- react-virtualized-auto-sizer
- react-window
- react-window-infinite-loader

Rollup [configuration](https://rollupjs.org/guide/en/#configuration-files) accepts an `external` property that takes an array of module's name like:

```
external: ['lodash']
```

It excludes the listed dependencies from the produced bundle.

**Comment by Orodan** [comment]
Hey I'll take care of it :)
