### ISSUE TITLE
Add the possibility to customize the scrollbar

### ISSUE THREAD

**Issue by frinyvonnick** [frinyvonnick/react-simple-infinite-loading#6]
It would be nice to have the possibility to customize the scrollbar. Here is an [example](https://github.com/bvaughn/react-window/issues/110#issuecomment-469061213).

There is a [codesandbox](https://codesandbox.io/s/vmr1l0p463) with a working example of code 👍

**Comment by eduaugustus** [comment]
Hi, can I do this?

**Comment by frinyvonnick** [comment]
Hi @eduaugustus 👋 thank you for considering contributing to this project! Sure feel free to open a pull request 👍

**Comment by frinyvonnick** [comment]
Hi @eduaugustus, do you need help on this ?

**Comment by eduaugustus** [comment]
Hi @frinyvonnick, I been thinkin about the solution, it's ok use react-custom-scrollbar?

**Comment by frinyvonnick** [comment]
You mean this repository https://github.com/malte-wessel/react-custom-scrollbars ? Sure it is the one used in the [codesandox](https://codesandbox.io/s/vmr1l0p463) I linked as example 😉

**Comment by eduaugustus** [comment]
ah okay, I'll  use this :D

**Comment by eduaugustus** [comment]
@frinyvonnick I've been thinking about solution in this weekend. The dev go set a prop in scroolbar like `customScroolbar` and with this react render a custom default scroolbar or dev should pass custom custom config?

**Comment by frinyvonnick** [comment]
You mean something like this:

```diff
<InfiniteLoading
  hasMoreItems={hasMore}
  itemHeight={40}
  loadMoreItems={fetchMore}
+ scrollbar
>
  {items.map(item => <div key={item}>{item}</div>)}
</InfiniteLoading>
```

If `scrollbar` prop is set we use `react-custom-scrollbars` otherwise we keep native scrollbar. We can also add a `scrollbarProps` prop to pass down options to `react-custom-scrollbars`.

```diff
<InfiniteLoading
  hasMoreItems={hasMore}
  itemHeight={40}
  loadMoreItems={fetchMore}
+ scrollbar
+ scrollbarProps={{ universal: true }}
>
  {items.map(item => <div key={item}>{item}</div>)}
</InfiniteLoading>
```

Does it seems correct?

**Comment by eduaugustus** [comment]
Hmm this style I think the scroll gonna have many props, I realy been think other way, if you pass `customScrollbar` prop, scrollbar has a condition render, if is true, render a default custom scrollbar, if false, render normal browser scroll

**Comment by eduaugustus** [comment]
@frinyvonnick LOL I'm sorry, I not understand before, but now it's clear, what you say is right hahaha

**Comment by frinyvonnick** [comment]
👋 @eduaugustus If you want some help you could create a pull request with your implementation so we could discuss about it together?
